{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "D:\\anaconda3\\lib\\site-packages\\flask_sqlalchemy\\__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.\n",
      "  warnings.warn(FSADeprecationWarning(\n",
      " * Running on http://localhost:9010/ (Press CTRL+C to quit)\n",
      "[2021-11-01 15:37:16,680] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1276, in _execute_context\n",
      "    self.dialect.do_execute(\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 593, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "sqlite3.OperationalError: no such table: user\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-2-f27abe063c22>\", line 52, in home\n",
      "    return render_template('home.html')\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\templating.py\", line 136, in render_template\n",
      "    ctx.app.update_template_context(context)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 838, in update_template_context\n",
      "    context.update(func())\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask_login\\utils.py\", line 379, in _user_context_processor\n",
      "    return dict(current_user=_get_user())\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask_login\\utils.py\", line 346, in _get_user\n",
      "    current_app.login_manager._load_user()\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\flask_login\\login_manager.py\", line 318, in _load_user\n",
      "    user = self._user_callback(user_id)\n",
      "  File \"<ipython-input-2-f27abe063c22>\", line 27, in load_user\n",
      "    return User.query.get(int(user_id))\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 1018, in get\n",
      "    return self._get_impl(ident, loading.load_on_pk_identity)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 1135, in _get_impl\n",
      "    return db_load_fn(self, primary_key_identity)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\loading.py\", line 286, in load_on_pk_identity\n",
      "    return q.one()\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3490, in one\n",
      "    ret = self.one_or_none()\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3459, in one_or_none\n",
      "    ret = list(self)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3535, in __iter__\n",
      "    return self._execute_and_instances(context)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3560, in _execute_and_instances\n",
      "    result = conn.execute(querycontext.statement, self._params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1011, in execute\n",
      "    return meth(self, multiparams, params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 298, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(self, multiparams, params)\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1124, in _execute_clauseelement\n",
      "    ret = self._execute_context(\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1316, in _execute_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1510, in _handle_dbapi_exception\n",
      "    util.raise_(\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 182, in raise_\n",
      "    raise exception\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1276, in _execute_context\n",
      "    self.dialect.do_execute(\n",
      "  File \"D:\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 593, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user\n",
      "[SQL: SELECT user.id AS user_id, user.username AS user_username, user.password AS user_password \n",
      "FROM user \n",
      "WHERE user.id = ?]\n",
      "[parameters: (2,)]\n",
      "(Background on this error at: http://sqlalche.me/e/13/e3q8)\n",
      "127.0.0.1 - - [01/Nov/2021 15:37:16] \"\u001b[35m\u001b[1mGET / HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, redirect, url_for, session, flash\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "from flask_wtf import FlaskForm\n",
    "from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField\n",
    "from wtforms.validators import InputRequired, Email, Length, ValidationError\n",
    "from flask_login import LoginManager, UserMixin, login_user, login_required, logout_user, current_user\n",
    "from flask_bcrypt import Bcrypt\n",
    "import sqlite3\n",
    "import requests\n",
    "import csv\n",
    "import pandas as pd\n",
    "\n",
    "app=Flask(__name__)\n",
    "bcrypt = Bcrypt(app)\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///users_database.db'\n",
    "app.config['SECRET_KEY']='thisisasecretkey'\n",
    "\n",
    "db = SQLAlchemy(app)\n",
    "login_manager = LoginManager()\n",
    "login_manager.init_app(app)\n",
    "login_manager.login_view = \"login\"\n",
    "\n",
    "from app import *\n",
    "try:\n",
    "    db.create_all()\n",
    "    print('Database successfully created.')\n",
    "except Exception as e:\n",
    "    print('Exception occurred',e)\n",
    "\n",
    "@login_manager.user_loader\n",
    "def load_user(user_id):\n",
    "    return User.query.get(int(user_id))\n",
    "\n",
    "class User(db.Model, UserMixin):\n",
    "    __tablename__ = 'User'\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    username = db.Column(db.String(15), nullable=False, unique=True)\n",
    "    password = db.Column(db.String(80), nullable=False)\n",
    "\n",
    "class RegisterForm(FlaskForm):\n",
    "    username = StringField(\"Username\", validators=[InputRequired(), Length(min=4, max=15)], render_kw={\"placeholder\": \"Username\"})\n",
    "    password = PasswordField(\"Password\", validators=[InputRequired(), Length(min=4, max=15)], render_kw={\"placeholder\": \"********\"})\n",
    "    submit = SubmitField(\"Sign Up\")\n",
    "    \n",
    "    def validate_username(self, username):\n",
    "        existing_user_username = User.query.filter_by(username=username.data).first()\n",
    "        if existing_user_username:\n",
    "            raise ValidationError(\"That username already exists:( Please choose a different one. \")\n",
    "\n",
    "class LoginForm(FlaskForm):\n",
    "    username = StringField(\"Username\", validators=[InputRequired(), Length(max=15)], render_kw={\"placeholder\": \"Username\"})\n",
    "    password = PasswordField(\"Password\", validators=[InputRequired(), Length(max=50)], render_kw={\"placeholder\":  \"Password\"})\n",
    "    submit = SubmitField(\"Login\")\n",
    "\n",
    "@app.route('/')\n",
    "def home():\n",
    "    return render_template('home.html')\n",
    "\n",
    "@app.route('/login', methods=['GET','POST'])\n",
    "def login():\n",
    "    form = LoginForm()\n",
    "    if form.validate_on_submit():\n",
    "        user = User.query.filter_by(username=form.username.data).first() \n",
    "        if user:\n",
    "            if bcrypt.check_password_hash(user.password, form.password.data):\n",
    "                login_user(user)\n",
    "                return redirect(url_for(\"dashboard\"))\n",
    "    \n",
    "        flash(\"User does not exist, or invalid username or password.\")\n",
    "    return render_template('login.html', form=form)\n",
    "\n",
    "@app.route('/dashboard', methods=['GET','POST'])\n",
    "@login_required\n",
    "def dashboard():\n",
    "    return render_template('dashboard.html')\n",
    "\n",
    "@app.route('/register', methods=['GET','POST'])\n",
    "def register():\n",
    "    form = RegisterForm()\n",
    "    if form.validate_on_submit():\n",
    "        hashed_password = bcrypt.generate_password_hash(form.password.data) #unrecognizable gabage\n",
    "        new_user = User(username=form.username.data, password=hashed_password)\n",
    "        db.session.add(new_user)\n",
    "        db.session.commit()\n",
    "        return redirect(url_for('login'))\n",
    "    return render_template('register.html', form=form)\n",
    "\n",
    "@app.route('/logout', methods=[\"GET\",\"POST\"])\n",
    "@login_required\n",
    "def logout():\n",
    "    session.clear()\n",
    "    logout_user()\n",
    "    return redirect(url_for('login'))\n",
    "\n",
    "@app.route(\"/post\")\n",
    "def post():\n",
    "    return render_template('post.html')\n",
    "\n",
    "@app.route(\"/contact\")\n",
    "def contact():\n",
    "    return render_template('contact.html')\n",
    "\n",
    "@app.route(\"/about\")\n",
    "def about():\n",
    "    return render_template('about.html')\n",
    "\n",
    "if __name__== '__main__':\n",
    "    app.run('localhost', 9010)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
